Add: Login With Steam
Structed/godot-playfab pull request #132
Opened 2023-12-11 14:27 UTC by TheDedemon

Hi, the feature can be tested on my branch **tests/login_with_steam**. I didn't put it with the feature to avoid importing external extension in the main branch.

2023-12-15 11:13 UTC, TheDedemon commented
I created an Issue corresponding to the PR, I forgot to add an example for the Steam Auth Ticket For Web API.

https://github.com/Structed/godot-playfab/issues/133

2023-12-18 09:11 UTC, Structed requested changes
A few bits of nitpicking, but overall really nice, thank you!

2023-12-18 09:18 UTC, Structed commented
I feel like this and the actual integration (with the code you have in the docs) should be it's own `godot-playfab-steam` addon. What are your thoughts on this, @TheDedemon?

2023-12-18 15:48 UTC, TheDedemon commented on docs/user/Logins/login-steam.md
> +- **info_request_parameters**: Flags for which pièce of info to return for the user
Sorry, some French xD

2024-06-01 17:27 UTC, Structed approved these changes

2024-06-01 17:27 UTC, Structed commented on docs/user/Logins/login-steam.md
> +2. Enter your Steam Web API Key
done

2024-06-01 17:27 UTC, Structed commented on docs/user/Logins/login-steam-godotsteam.md
> +They are many possibles errors, the most commons are:
resolved

2024-06-01 17:35 UTC, merged