Patch Issue #81
Structed/godot-playfab pull request #82
Opened 2022-11-12 05:45 UTC by zymsbgt

2022-11-12 05:46 UTC, zymsbgt commented
This patches issue #81 that I created a while ago. Only bug to my solution is the two login buttons can turn green after each method is used at least once.

2022-11-12 07:18 UTC, Structed requested changes
Thank you for your PR! However, there are  quite a few changes that are not part of the change. Like removing GUT, changing the position of UI elements and adding mono specific attributes.

Can you please remove these?
Thank you!

2022-11-12 07:43 UTC, zymsbgt commented
Sorry about the additional changes, those were an oversight. Would it be more advisable to use the Standard or Mono edition of Godot when contributing to this repository?

2022-11-12 08:22 UTC, Structed commented
No worries - thanks for making the changes!
I will test it later, as I am on the go.

It does not matter which edition you are using. I just want to keep it compatible with the non-mono version, as this seems to have the most proliferation.
That is also the reason for that I have done a full GDScript-only implementation.

2022-11-12 19:45 UTC, Structed commented
Ok, I checked this out properly now. I think this should be implemented a little different.

First, the new implementation is inconsistent, as it only marks both buttons green when using AnonLogin.

However, I think it should only mark the respective login button as green that was used. Basically:if there is already a local login saved, mark the relevant button green.

2022-11-12 19:47 UTC, Structed requested changes

2022-11-12 19:48 UTC, Structed commented
Ok, I checked this out properly now. I think this should be implemented a little different.

First, the new implementation is inconsistent, as it only marks both buttons green when using AnonLogin.

However, I think it should only mark the respective login button as green that was used. Basically:if there is already a local login saved, mark the relevant button green.

2022-11-13 04:36 UTC, zymsbgt commented
I have already reverted all the unnecessary changes that were made on my editor. The respective login button turns green when it is used. The only issue I've found is that both login buttons would be green if one login button was used, then the back button was clicked and then the other login button was used.

2022-11-14 16:24 UTC, Structed commented
> I have already reverted all the unnecessary changes that were made on my editor
Sorry about that, I was just messing about with the review system in GitHub 😬

2022-11-14 16:26 UTC, Structed commented
> The respective login button turns green when it is used. The only issue I've found is that both login buttons would be green if one login button was used, then the back button was clicked and then the other login button was used.

I see what you mean, but I'd do it differently. In fact, I already implemented saving the login token, so we could enable auto-login (#27). AT the very least, it should mark the button green, where we already have the data cached.

I'll provide an updated implementation a bit later.

2022-11-15 04:55 UTC, zymsbgt commented
Alright. I'm not sure how to implement that, so I'll leave it to you.

2022-11-16 08:49 UTC, Structed approved these changes

2022-11-16 08:51 UTC, Structed commented
@zymsbgt thanks so much for the idea and the POC implementation! I hope the change I just pushed is in your interest as well. I think it's a bit more consistent, and as said above, it's the next step to #27, which is exciting!

2022-11-16 12:21 UTC, merged